import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";
import Nav from "../components/Nav";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Nav />
      <Head>
        <title>Aktualne kursy kryptowalut - KryptoKurs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>KryptoKurs</h1>
      <Footer />
    </div>
  );
}
