import Head from "next/head";
import Cryptos from "../components/Cryptos";
import Featured from "../components/Featured";
import Header from "../components/Header";
import Info from "../components/Info";
import MoreFeatured from "../components/MoreFeatured";
import Poradnik from "../components/Poradnik";
import Stats from "../components/Stats";
import { getFeaturedPost } from "../services/featuredPostIndex";
import { getPosts } from "../services";
import { getPoradnikPosts } from "../services/poradnikPostsIndex";
import styles from "../styles/Home.module.css";

export default function Home({ stats, featuredPost, posts, poradnikPosts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Aktualne kursy kryptowalut - KryptoKurs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Stats stats={stats} />
      <Cryptos />
      <Featured featuredPost={featuredPost} />
      <MoreFeatured posts={posts} />
      <Poradnik poradnikPosts={poradnikPosts} />
      <Info />
    </div>
  );
}

export async function getStaticProps() {
  const resStat = await fetch(`https://api.coingecko.com/api/v3/global`);
  const statData = await resStat.json();

  const featuredPost = (await getFeaturedPost()) || [];

  const posts = (await getPosts()) || [];

  const poradnikPosts = (await getPoradnikPosts()) || [];

  return {
    props: {
      stats: statData,
      featuredPost,
      posts,
      poradnikPosts,
    },
  };
}
