import Head from "next/head";
import Cryptos from "../components/Cryptos";
import Header from "../components/Header";
import Stats from "../components/Stats";
import styles from "../styles/Home.module.css";

export async function getStaticProps() {
  const resStat = await fetch(`https://api.coingecko.com/api/v3/global`);
  const statData = await resStat.json();

  return {
    props: {
      stats: statData,
    },
  };
}

export default function Home({ stats }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Aktualne kursy kryptowalut - KryptoKurs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Stats stats={stats} suppressHydrationWarning={true} />
      <Cryptos />
    </div>
  );
}
